yuzutech/kroki

Makefile
blockdiag/requirements.txt
docs/modules/ROOT/pages/architecture.adoc
mermaid/package-lock.json
mermaid/package.json
nomnoml/Makefile
nomnoml/package-lock.json
nomnoml/package.json
server/ops/docker/jdk11-alpine/Dockerfile
server/ops/docker/jdk11-slim-stretch/Dockerfile
server/ops/docker/jdk8-alpine/Dockerfile
server/pom.xml
server/src/main/java/io/kroki/server/service/HelloHandler.java
server/src/main/java/io/kroki/server/service/Mermaid.java
server/src/main/java/io/kroki/server/service/Nomnoml.java
server/src/main/java/io/kroki/server/service/Svgbob.java

- Jinja2 from 2.10 to 2.10.1
- Werkzeug from 0.14.1 to 0.15.3
- Mermaid from 8.0.0 to 8.2.6
- Nomnoml from 0.3.0 to 0.6.1
- Jackson data-bind from 2.9.8 to 2.9.9.3

Security upgrade

---

.travis.yml

Travis does the following:
- installs the dependencies
- builds the project with `maven`
The selected JDK is OpenJDK 12 but it can be changed for a lower version if needed.
I would have liked to add containers builds to the CI but I did not manage to build them locally for testing.
I hope it helps. Thanks in advance for your feedback.

Add Travis to project

---

README.adoc

I just added a note about the fact that `sudo` is not needed to build the containers depending on your configuration.
Thanks for your feedback.

Add note about using docker with sudo

---

.travis.yml
Makefile
docs/modules/ROOT/pages/architecture.adoc
server/ops/docker/build-static-svgbob
server/ops/docker/jdk8-alpine/Dockerfile
server/src/main/java/io/kroki/server/service/HelloHandler.java

- Updated `svgbob` from `0.4.1` to `0.4.2`
- `svgbob` installation is now done using `cargo` instead of a `git clone`
- Added container build to Travis Continuous Integration
Thanks in advance for your feedback.

Fix svgbob container build and add build to Travis

---

docs/modules/setup/pages/manual-install.adoc
server/ops/docker/jdk11-alpine/Dockerfile
server/ops/docker/jdk11-slim-stretch/Dockerfile
server/ops/docker/jdk8-alpine/Dockerfile
server/src/main/java/io/kroki/server/Server.java
server/src/main/java/io/kroki/server/security/SafeMode.java
server/src/main/java/io/kroki/server/service/C4Plantuml.java
server/src/main/java/io/kroki/server/service/Plantuml.java
server/src/test/java/io/kroki/server/security/SafeModeTest.java
server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java

The safe mode restricts access to files on the file system and on the network.
PlantUML `!include` directive can be enabled using `KROKI_SAFE_MODE=unsafe`.

resolves #49 introduces a safe mode

---

docs/modules/setup/pages/install.adoc

Just a minor thing, but there's no particular reason to publicly expose the supporting container ports (which is what the `ports` directive does). `expose` only exposes the ports to other containers in the same docker network.

Expose supporting containers internally, not publicly

---

.github/workflows/main.yaml

- Tests have been migrated to GitHub Actions
- Tests are split in 2 jobs:
- BlockDiag tests (approximately: 2 minutes of build time)
- containers building and smoke testing (approximately: 19 minutes of build time)
- Travis CI configuration is still there but it can be removed once the «go» to GitHub Action has been decided
I hope it satisfies the needs specified in #165.
Thanks for your feedback.

Migrate tests to GitHub Actions

---

.github/workflows/main.yaml

`actions-setup-docker` seems unstable/heavyweight and had failed quite a lot recently so trying a new approach taken from the "official" Docker GitHub Actions repository: https://github.com/docker/github-actions

Use a simpler setup for Docker

---

bytefield/index.js

Otherwise the namespaces will be missing and the browser won't show the image when served directly using "image/svg+xml" content-type.

Do not use the embedded mode in bytefield

---

server/README.adoc
server/src/main/java/io/kroki/server/security/SafeMode.java
server/src/main/java/io/kroki/server/service/C4Plantuml.java
server/src/main/java/io/kroki/server/service/Plantuml.java
server/src/main/java/io/kroki/server/service/Vega.java
server/src/test/java/io/kroki/server/security/SafeModeTest.java
server/src/test/java/io/kroki/server/service/C4PlantumlServiceTest.java
server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java
server/src/test/resources/whitelist_empty_lines.txt
server/src/test/resources/whitelist_invalid.txt
server/src/test/resources/whitelist_mixed.txt
server/src/test/resources/whitelist_valid.txt

We generate images as part of our build chain and so we trust the URLs and other libraries that we want to use as includes. The current includes blocking is heavy handed. This should allow import path includes as well as enabling a whitelist of regexes for anyone who wants to allow including only a subset of URLs that they actually trust.
Note: I would advise repeating my analysis of PlantUML's `ImportedFiles` to verify that for regular file imports it only permits the inclusion of files that are actually on the include path (my analysis showed that it is a bit too strict as you cannot have `!include foo/bar.puml` because the `getSystemFolder()` will then return `$DIR_FROM_SEARCH_PATH/foo` which is not explicitly one of the files on the search path... but that seems sufficiently strict …

Allow configuration of PlantUML includes

---

docs/modules/setup/pages/kroki-cli.adoc

Instead of linking to a specific version (and falling out of date), just link to the releases listing, which will show latest on top.

kroki-cli doc: Link to releases page

---

docs/modules/setup/pages/configuration.adoc
pom.xml
server/ops/docker/jdk11-alpine/Dockerfile
server/src/main/java/io/kroki/server/Server.java
server/src/main/java/io/kroki/server/log/Logging.java
server/src/test/java/io/kroki/server/ServerConfigTest.java
server/src/test/java/io/kroki/server/ServerListenTest.java

- KROKI_LISTEN has higher precedence than KROKI_PORT
- Support `tcp://ip:port` value on KROKI_PORT (this value can be automatically set by the container runtime: k8s, Docker...)
- Set KROKI_CONTAINER_SUPPORT environment variable on the Docker image to indicate that we are running in a container
resolves #576

KROKI_LISTEN option to start listening on an address

---

blockdiag/Dockerfile

Sometimes `gunicorn` fails to start, I believe that the `--preload` option can improve the situation: https://docs.gunicorn.org/en/stable/settings.html#server-mechanics

Load application code before the worker processes are forked

---

server/ops/docker/jdk11-alpine/Dockerfile

With this change, CJK characters are now correctly rendered when converting to PNG:
For reference, here's the result using http://www.plantuml.com/
The package [`font-noto-cjk`](https://pkgs.alpinelinux.org/package/edge/community/x86_64/font-noto-cjk) (and all its dependencies) is quite large, approximately 200MB.
Here's the Docker image size before (0.10.0) and after (latest):
```
yuzutech/kroki     0.10.0     434MB
yuzutech/kroki     latest     650MB
```
resolves #386

resolves #386 install CJK font

---

bpmn/Dockerfile
bytefield/ops/docker/alpine/Dockerfile
excalidraw/Dockerfile
mermaid/Dockerfile
nomnoml/ops/docker/alpine/Dockerfile
vega/ops/docker/alpine/Dockerfile
wavedrom/ops/docker/alpine/Dockerfile

Also explicit CLI option on `pkg-fetch`:
- `-n`: Node version (node10)
- `-p`: Platform (alpine)
- `-a`: Architecture (x64)

Use fixed versions to improve build reliability

---

server/ops/docker/build-static-pikchr

the previous version of this dockerfile didn't build a static binary, but that issue was masked because the image used to build the binary, and the image where the binary ran, both have the required dynamic libraries.
This commit fixes the issue, by passing GCC the `-static` flag to build a static binary.

tell GCC to build a static binary for pikchr

---

server/src/main/java/io/kroki/server/Server.java
server/src/test/java/io/kroki/server/ServerTest.java

The CORS handling mechanism of vertx-web should allow an HTTP header
with `Origin: null`, but currently it doesn't, and it causes requests to Kroki 
with that header to fail; see https://github.com/vert-x3/vertx-web/issues/1933
for the details.
This interferes with using Kroki in some scenarios, for example, using it
from a browser (javascript) in a webpage that is served from a `file://` URL.
While that bug is fixed, this commit adds a workaround that enables
Kroki to handle that header value properly.
The workaround just defines a regexp that allows any value in that
header; vertx-web just matches the value using that regexp, and if it
matches the request continues its processing as normal.

workaround for issue with CORS and Origin: null in vertx-web

---

.github/workflows/dockerhub-description.yml
DOCKERHUB-COMPANION.md

As a follow up to the issue https://github.com/yuzutech/kroki/issues/698 and PR https://github.com/yuzutech/kroki/pull/737 for the companion images.
A proposal with one single file to describe the companion image repositories on Docker hub. 
It is differences between the images but I think it is better to have a simple description in docker hub and instead point to to the docs where information about port setting etc is described.
WDYT @Mogztter?

Update companion images description on Docker Hub

---

docs/antora.yml
docs/modules/setup/nav.adoc
docs/modules/setup/pages/about-docker-podman.adoc
docs/modules/setup/pages/install.adoc

This PR addresses issue #797
There are multiple commented commits on the same file.

docs(install.adoc) Add podman guide

---

server/ops/docker/build-static-svgbob

Svgbob 0.5.0 supports shape tagging and styling

Bumb svgbob from 0.4.2 to 0.5.3

---

docs/modules/setup/nav.adoc
docs/modules/setup/pages/install.adoc
docs/modules/setup/pages/use-docker-or-podman.adoc
docs/modules/setup/pages/use-kubernetes.adoc

Pull request for issue #828
Make the install documentation as follows:
> Install
> - Using Docker or Podman
> - Using Kubernetes
> - Manual install
To preserve contributor history, instead of just copying the content to the new files, this method is used: https://devblogs.microsoft.com/oldnewthing/20190919-00/?p=102904
Modifications to date:
After removing any unused attributes from the split out pages, those remaining are only used on the page where they are defined. I didn't see the need to propagate any to the `antora.yml` file as yet. If it should happen that this is not the case then it would be good to move them.
Install page:
- Remove redundant content from the page.
- Rework the introductions to the page and installation methods.
- Standardise styles for linking to pages and …

resolves #828 split install page

---

pom.xml
server/pom.xml
server/src/main/java/io/kroki/server/error/ErrorHandler.java
server/src/main/java/io/kroki/server/error/ErrorImage.java
server/src/test/java/io/kroki/server/ErrorImageTest.java
server/src/test/java/io/kroki/server/error/ErrorHandlerTest.java

Use svgSalamander to create SVG and PNG images.
For reference, Batik adds ~7mb of dependencies.
resolves #842

resolves #842 creates SVG and PNG error images

---

mermaid/Dockerfile
mermaid/package-lock.json
mermaid/package.json
mermaid/src/worker.js
mermaid/tests/test.js

We were using `innerHTML` which converts `<br/>` to `<br>`. It's interesting to note that `<br>` is valid HTML but invalid XML.
To serialize an SVG to string, we must use `new XMLSerializer().serializeToString(node)`.
Reference: https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer/serializeToString
resolves #924
//cc @cowboy

resolves #924 return valid SVG/XML

---

docs/modules/setup/pages/usage.adoc
server/README.adoc

As it may not be the default `python` on an OS any more, we should make
it possible to run against Python 2 and Python 3.

Use Python-version agnostic helpers

---

server/src/main/java/io/kroki/server/service/HelloHandler.java
server/src/test/java/io/kroki/server/service/HelloServiceTest.java

Also add basic tests for the Hello page:
- Content-Type text/html
- Start of page is HTML
- Table with the right number of version numbers
Fixes #1053

resolves #1053 set Content-Type on hello page

---

.dockerignore

During `make buildDockerImages`, I noticed that 1.8GB (or GO :wink:) have to be sent to the docker builder. This significantly reduces the context that has to be transferred.

Shrink docker build context

---

docs/modules/setup/pages/configuration.adoc

Hello,
as discussed in #1219, I have added example commands for running kroki in podman/docker with SSL.
If you have suggestions for improvement, please let me know.

#1219 Add an example for enabling SSL.

---

.github/workflows/cve-scan.yml

resolves #1266 run a CVE scanner (nightly)

---

server/src/main/java/io/kroki/server/error/UnsupportedFormatException.java

Updates the "unsupported output format" error message for non-HTML responses to be aligned with the HTML response.
The previous implementation caused the `serviceName` to be used in place of the `supportedFormat` and vice versa, e.g. `Unsupported output format: jpg. Must be one of mermaid for png or svg.`
The other option would have been to swap the arguments, but I figured the consistent error message was preferred.

Align 'unsupported output format' error messages

---

docs/modules/setup/pages/third-party-tools.adoc

I'm the maintainer of [Kroki.jl](https://bauglir.github.io/Kroki.jl/stable) and, having just released a new version of the package, I was hoping you'd consider including the package in the list of third-party tools that rely on Kroki.
The Julia package makes it easy to integrate diagrams that are supported by Kroki throughout the Julia ecosystem, e.g. in documentation, notebooks, etc.

Add Julia integration to third-party tools in the documentation

---

docs/modules/setup/pages/third-party-tools.adoc

Listing Hugo and MkDocs integrations.
For Hugo, found multiple community sources, but I could not say which one works (best):
https://github.com/netspective-studios/hugo-shortcode-diagram
https://github.com/jmooring/hugo-testing/tree/hugo-forum-topic-36924
Can this be integrated nonetheless?

docs: Add reference to MkDocs Kroki plugin

---

server/ops/docker/Cargo.toml
server/ops/docker/build-static-svgbob

Addresses #970 by converting the build-static-svgbob to use a Cargo.toml file instead of specifying version directly
I wasn't able to get a full build of kroki to run on my machine but this did seem to work correctly with `COPY --from=kroki-builder-static-svgbobs:latest /home/rust/.cargo/bin/svgbob /usr/bin/svgbob` from `server/ops/docker/jdk11-alpine/Dockerfile`

resolves #970 use cargo.toml to install svgbob

---

docs/modules/setup/examples/encode.ex
docs/modules/setup/pages/encode-diagram.adoc

Enhances the docs -> https://docs.kroki.io/kroki/setup/encode-diagram to include an Elixir example encoding a graph.

Add an Elixir encode example

---

server/ops/docker/build-static-svgbob
server/ops/docker/jdk11-alpine/Dockerfile

- using official builder image
- reduce [Supply_chain_attack](https://en.wikipedia.org/wiki/Supply_chain_attack)
- rust-musl-builder has [not maintained in a while](https://github.com/emk/rust-musl-builder)
- change svgbob_cli builder image(rust-musl-builder:1.57.0 to rust:1.64-slim-bullseye)
- fixed: builder binary path
- filed:  specify target platform(x86_64-unknown-linux-musl)
```
FROM rust:1.64-slim-bullseye AS builder
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo install svgbob_cli --version 0.6.6 --target x86_64-unknown-linux-musl
FROM alpine:3.16
COPY --from=builder /usr/local/cargo/bin/svgbob_cli /usr/bin/svgbob_cli
```

chore(build-deps): use official builder image(rust-musl-builder:1.57.0 to rust:1.64-slim-bullseye)

---

mermaid/package-lock.json
mermaid/package.json
mermaid/src/index.js
mermaid/src/worker.js

This PR tries to implement the ability of configuring some options of mermaid using query params of the GET request.
This will only handle properties that have string values and won't handle anything else at the moment. This is mostly because I am not sure how to send configuration values of `flowchart.useMaxWidth`. If there is some clarity on that I can implement that too.
Fixes #1326

feat: allow mermaid to be configured via some query params

---

docs/modules/ROOT/pages/architecture.adoc

This fixes the docker image name for blockdiag and adds the docker image name for the main docker image.

docs: fix docker image names

---

docs/modules/setup/pages/third-party-tools.adoc

Hi! This is a tiny change to fix capitalization of GitLab's name.

Fix GitLab capitalization

---

SECURITY.md
diagrams.net/assets/stencils/aws/deployment_management.xml
diagrams.net/assets/stencils/office/servers.xml
docs/modules/setup/pages/configuration.adoc
server/src/main/java/io/kroki/server/service/Plantuml.java
server/src/main/resources/c4.puml

This PR fixes a few typos I spotted.

Fixing typos

---

docs/modules/setup/pages/diagram-options.adoc

This PR removes two sections that are given twice on the page [Diagram options](https://docs.kroki.io/kroki/setup/diagram-options/):
- Structurizr
- Svgbob

Docs, diagram options: remove duplicate sections

---

docs/modules/setup/pages/diagram-options.adoc
server/src/main/java/io/kroki/server/service/D2.java

This PR addresses and hopefully closes #1466.

D2: fix incorrect color number for theme 'Neutral grey'

---

wireviz/requirements.txt

Cleanup wireviz requirements.txt
* update `Flask` from 2.2.2 to 2.2.3
* update `Werkzeug` from 2.2.2 to 2.2.3
* remove unused `funcparserlib` module
* remove unused `webcolors` module
* add `Jinja2` dependency to version 3.1.2
* add `MarkupSafe` dependency to version 2.1.2
* add `Pillow` dependency to version 9.4.0
* add `PyYAML` dependency to version 6.0
* rename `click` to lower case

Wireviz: Cleanup requirements; update Flask and Werkzeug to 2.2.3

---

ci/tests/diagrams/periodic-table.tex
ci/tests/smoke.js
docker-bake.hcl
server/ops/docker/jdk11-jammy/Dockerfile
server/src/main/java/io/kroki/server/Server.java
server/src/main/java/io/kroki/server/service/TikZ.java
tikz/tikz2svg

This change adds support for converting PGF/TikZ to JPEG, PDF, PNG, and SVG.
The user input is lightly pre-processed.  If the user input contains a `\docmentclass` command, the user input is passed to latex untouched. Otherwise, a `\documentclass` command is derived from the output format and prepended to the user input then passed to latex.
The flow from here is as follows:
- For JPEG and PNG: Use `latex` to convert the user input to PDF.  Then convert the PDF to JPEG or PNG using `pdftocairo`.
- For PDF: Use `latex` to convert the user input to PDF.
- For SVG: Use `latex` to convert the user input to DVI.  Then convert the DVI to SVG using `dvisvgm`.
I also considered `pdftocairo` and `pdf2svg` to generate SVG.  `pdf2svg` is no longer maintained and the author recommends `pdftocairo` …

Add PGF/TikZ support

---

.github/workflows/main.yaml
.github/workflows/nightly.yaml
Makefile
bpmn/Dockerfile
diagrams.net/Dockerfile
docker-bake.hcl
excalidraw/Dockerfile
mermaid/Dockerfile
server/ops/docker/.cargo/config
server/ops/docker/jdk11-jammy/Dockerfile
server/src/test/java/io/kroki/server/service/VegaServiceTest.java
vega/tests/test.js

Builds an `arm64` variant of the main Kroki Docker image by leveraging the changes introduced in #1476. All images should now natively support the ARM architecture. This includes the following changes:
- Creates a `nightly` workflow to build the multi-arch images every night at 02:00 UTC.
- Restricts the Docker Buildx builder to 2 parallel threads. This matches the 2 cores available on the GitHub CI runners and prevents timeouts during the build process.
- Runs a [free disk space](https://github.com/jlumbroso/free-disk-space) action at the start of the CI workflow to recover extra disk space from the CI runner. This is now necessary to successfully complete the build process.

Build arm64 main image

---

docs/modules/setup/pages/diagram-options.adoc
server/src/main/java/io/kroki/server/service/D2.java

This PR adds further themes available for d2 diagrams to the documentation.
Were great if the docs could be redeployed after merge so that changes take effect.

Documentation: complete available themes for d2 diagrams

---

docs/modules/setup/pages/configuration.adoc
server/src/main/java/io/kroki/server/Server.java
server/src/test/java/io/kroki/server/ServerSSLTest.java

Allows the SSL certificate and private key to be passed to the Docker image as a file path instead of a string (see #1512). This includes the following changes:
- Adds two new environment variables `KROKI_SSL_KEY_PATH` and `KROKI_SSL_CERT_PATH`. These are given lower priority than the existing `KROKI_SSL_KEY` and `KROKI_SSL_CERT` variables in case of multiple definitions.
- Adds new server tests to check for correct SSL setup in both possible cases (certificate + key provided as strings or as paths).
- Updates the documentation to describe both possible options.

Allow SSL certificate to be passed as a file path

---

ci/tasks/update-versions.js
docs/antora.yml
server/ops/docker/jdk11-jammy/Dockerfile
server/src/main/java/io/kroki/server/service/Graphviz.java

Use pre-built binary for GraphViz

---

bpmn/Dockerfile
diagrams.net/Dockerfile
excalidraw/Dockerfile

Adds missing `TARGETARCH` and `TARGETOS` arguments to the BPMN, Diagrams.net, and Excalidraw Dockerfiles to fix the broken `arm64` builds of these images. Without these arguments, the binaries are always built for the host architecture (currently `amd64`) instead of the target.

Add missing Docker arguments for arm64 builds

---

server/src/main/java/io/kroki/server/Server.java
server/src/main/java/io/kroki/server/action/CommandStatusHandler.java
server/src/main/java/io/kroki/server/error/ErrorHandler.java
server/src/main/java/io/kroki/server/log/Logging.java
server/src/main/java/io/kroki/server/service/D2.java
server/src/main/java/io/kroki/server/service/Excalidraw.java
server/src/main/java/io/kroki/server/service/Wireviz.java
server/src/main/resources/web/error.html
server/src/main/resources/web/root/css/main.css
server/src/test/java/io/kroki/server/action/CommanderTest.java

Previously, we could return `404 OK` which was misleading.

Improve error code status

---

docs/modules/setup/pages/diagram-options.adoc

This PR adds documentation for the newly added option 'sketch' for D2 diagrams.
**Side note**: https://docs.kroki.io hasn't deployed for quite some time now, documentation changes that are present for quite some time now are not reflected yet. Could you please regenerate the Antora based docs? Thanks!

D2 diagrams: document option 'sketch'

---

diagrams.net/Dockerfile
diagrams.net/package-lock.json
diagrams.net/package.json
diagrams.net/src/browser-instance.js
excalidraw/Dockerfile
excalidraw/package-lock.json
excalidraw/package.json
excalidraw/src/browser-instance.js

Upgrade to Alpine 3.18

---

server/src/main/java/io/kroki/server/error/ErrorHandler.java

```console
$ http :8000/graphviz/svg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ "Origin: lsp:///bad"
HTTP/1.1 500 Internal Server Error
content-length: 41
content-type: text/plain
Error 500: CORS Rejected - Invalid origin
```
```console
$ http :8000/graphviz/svg/eNpLyUwvSizIUHBXqPZIzcnJ17ULzy_KSanlAgB1EAjQ "Origin: lsp:///bad"
HTTP/1.1 403 Forbidden
content-length: 41
content-type: text/plain
Error 403: CORS Rejected - Invalid origin
```

Invalid CORS now returns a 403 (instead of 500)

---

mermaid/src/index.js

I am using fly.io to deploy and it has health checks, but you can't specify a payload to send, has to be a simple request without any parameters.
Adds `health` route (any method) that renders an example mermaid diagram to ensure the worker is responsive.
Related issues in show-me chatgpt plugin project:
https://github.com/bra1nDump/show-me-chatgpt-plugin/issues/42
https://github.com/bra1nDump/show-me-chatgpt-plugin/issues/26

Adding a health check that can be used to determine if the worker is healthy

---

ci/tests/smoke.js
diagrams.net/src/index.js

Fix #1602
Copy the same workaround as in mermaid https://github.com/yuzutech/kroki/blob/main/mermaid/src/index.js#L28-L29

Fix #1602: Error with diagramsnet, when using parameters

---

ci/tests/smoke.js
docs/modules/setup/pages/diagram-options.adoc
server/src/main/java/io/kroki/server/service/D2.java

Adds support for alternate D2 layout engines (see [documentation](https://d2lang.com/tour/layouts/)). Currently this includes both the default layout engine, `dagre`, and an open-source third-party alternative, `ELK`.
The `TALA` engine is not supported because it is proprietary (non-free) and closed-source.
Output with no layout specified (`dagre` is used by default):
```
curl http://localhost:8000/d2/svg/eNo9zLkRgDAMRNF8q3ADtEAvvrExBvpPkH9A8rSjkdZvuwuKjpHMrILBLFhV_3xgw6RuRvRsupp50jM06LnIy6nJbyIXXF-3Hm6y-X5cSiFx > default.svg
```
Output with `layout=elk`:
```
curl http://localhost:8000/d2/svg/eNo9zLkRgDAMRNF8q3ADtEAvvrExBvpPkH9A8rSjkdZvuwuKjpHMrILBLFhV_3xgw6RuRvRsupp50jM06LnIy6nJbyIXXF-3Hm6y-X5cSiFx?layout=elk > elk.svg
```
Closes #1557

Add D2 layout engine option

---

ci/tests/smoke.js
docs/modules/setup/pages/diagram-options.adoc
server/src/main/java/io/kroki/server/service/D2.java
server/src/main/java/io/kroki/server/service/PlantumlCommand.java

Adds support for the PlantUML `-nometadata` argument to prevent the diagram source code from being included as metadata in the generated SVG or PNG files. See the PlantUML [documentation](https://plantuml.com/command-line) for more information.
Default output (source code included as metadata at the bottom of the file):
```
curl http://localhost:8000/plantuml/svg/eNpljzEPgjAQhff-iguTDFQlcYMmuru5mwNO0tCWhjY6GP-7LRJTdHvv7r67d26QxuKEGiY0gyML5Y65b7GzEvblIalYbAfs6SK9oqOSvdFkPCi6ecYmaj2aXhFkZ5QmgycD2Ogg-V3SI4_OyTjgR5OzVwqc0NECNEHydtR2NGH3TK2dHjtSP3zViPmQd9W2ERmgg-iv3jGW4MC5-L-wTEJdi1XeRENRiFWOtMfnrclriQ5gJD-Z3x9beAM= > default.svg
```
```xml
<?xml version="1.0" encoding="us-ascii" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" …
```

Add PlantUML no-metadata option

---

docs/modules/setup/pages/configuration.adoc
excalidraw/Dockerfile
excalidraw/assets/index.html
excalidraw/src/worker.js

Replace pull request #1652 and fix issue #1651

Add (optional) excalidraw custom asset path

---

docs/modules/setup/pages/third-party-tools.adoc

Adds the [jekyll-kroki](https://github.com/felixvanoost/jekyll-kroki) plugin to the list of 3rd-party tools that use Kroki.

Add jekyll-kroki to list of 3rd-party tools

---

docs/modules/setup/pages/configuration.adoc
server/src/main/java/io/kroki/server/Server.java

I've deployed Kroki to a setup where the XFCC header size is larger than the 8kb limit. This let's the user set their desired max header size.

Add option for max header size

---

.github/workflows/main.yaml
.github/workflows/release.yml
ci/tasks/update-versions.js
docker-bake.hcl
pom.xml
server/README.adoc
server/ops/docker/jdk17-jammy/Dockerfile

This updates the Java version Kroki uses to Java 17.
For now this is a draft as I found it a bit difficult to test Kroki locally.  (I have IPv6 disabled which some tests seem to require and at least one of the Vega tests fails locally because of some Node.js stuff not being in place as expected.  And even with a hack to get Node.js working it seems to generate a different SVG on my machine.)
Fixes #1688 when merged.

Update Docker image to Java 17

---

diagrams.net/src/index.js
excalidraw/src/index.js
mermaid/src/index.js

From #1760 
Allow changing max body sizes using environment variables on mermaid, diagrams.net and excalidraw.
Would it be better to use three different variables, one for each tool (e.g. KROKI_DIAGRAMSNET_MAX_BODY_SIZE) ?

Change max body size using envvars when rendering diagramas

---

vega/package-lock.json
vega/package.json
vega/tests/test.js

- removes chai, dirty-chai and mocha
- upgrades canvas to 3.0.0 (use N-API and prebuild-install)
- upgrades development dependencies
- upgrades vega to 5.30.0
- upgrades vega-lite to 5.21.0

chore(deps): use Node built-in test runner

---

server/src/main/java/io/kroki/server/service/Plantuml.java
server/src/main/java/io/kroki/server/service/PlantumlCommand.java

I have found a way of passing the `plantuml.include.path` property to the native plantuml library.
It's worth noting that, plantuml has a `-D` parameter which sets value of global preprocessing variable as described here: https://plantuml.com/command-line, however when built using GraalVM into native library, the GraalVM handling of the `-D` parameter (described here: https://www.graalvm.org/latest/reference-manual/native-image/guides/use-system-properties/) takes precedence, which is the reason why this fix works.
I have added debug log message to add ability to see the exact plantuml command parameters which makes it easier to debug any problems with it, if necessary.
Please let me know what do you think.
Fixes #1765

fix(plantuml): pass plantuml.include.path property to native plantuml binary

---

diagrams.net/src/index.js

Hi team,
I found that `diagrams.net` is missing `/health` for the health check. That may lead to a failure in K8s when starting the instance, so I created this pull request to support it.
Please review it and give me comments if any!
Thank you!

chore: diagrams.net - add /health API for health checks 

---

docs/modules/setup/examples/kroki-docker-compose.yml

Document the fact that, if /tmp is explicitly mounted into kroki container, the option exec: ought to be used.
Fixes: #1874

Document /tmp:exec

---

docs/modules/setup/pages/third-party-tools.adoc

Hello, I created a Python-Markdown extension.
If possible, could you please add the 3rd-party list?
- `pip install markdown-kroki`
- https://hkato.github.io/markdown-kroki/
- https://github.com/hkato/markdown-kroki

chore(docs): add python-markdown extension to list of 3rd-party tools

---

docs/modules/setup/examples/encode.cs

- `ZLibStream` has been added in .NET 6.0
- `Base64Url` has been added in .NET 9.0
- Append the checksum-trailer to `MemoryStream` directly

Modernize C# example

---

docs/antora.yml
server/ops/docker/jdk17-noble/Dockerfile
server/src/main/java/io/kroki/server/service/D2.java

D2 recently released [v0.7.0 ](https://github.com/terrastruct/d2/releases/tag/v0.7.0) which adds much among others adds better support for c4 model diagrams. See https://d2lang.com/blog/c4 and a new c4 theme.
It would be great to have the new version in the next kroki release

Update D2 to 0.7.0 & add new C4 theme

---

bpmn/Dockerfile
diagrams.net/Dockerfile
excalidraw/Dockerfile
mermaid/Dockerfile

Otherwise, Chrome cannot write files when running Docker in read-only.
Using `/tmp` directory seems like a good default value.
resolves #1910

fix: set XDG_CONFIG_HOME and XDG_CACHE_HOME to temp directory

---

tikz/tikz2svg

The tikz svg output uses dvisvgm.  Dvisvgm requires the input latex to specify the PGF dvisvgm driver by passing the dvisvgm option via the documentclass.
Previous to this change, the kroki tikz output would generate a correct documentclass if the user didn't provide one.  However, if the user provided a documentclass the kroki tikz output would use it as is.  This allowed users to specify an incorrect documentclass and then get undesired output.
Fix by overwriting any user-provided documentclass.  The implication is that users can no longer provide their own documentclass.  However, I couldn't find any convincing usecases for this in the context of diagrams.
This change implements option 1 from
https://github.com/yuzutech/kroki/issues/1870#issuecomment-2822066909. The alternative of …

Fix bad tikz render due to bad documentclass
