- docs/modules/setup/pages/install.adoc
> resolves #1 explain how to map container port to host port

- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/error/ErrorHandler.java
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- server/src/main/resources/web/error.html
- server/src/main/resources/web/hello.html
- server/src/main/resources/web/root/assets/logo.svg
- server/src/main/resources/web/root/css/main.css
Avoid paths resolutions when Kroki is behind a reverse proxy with a virtual subdirectory.
> resolves #16 embed assets in the HTML pages

- nomnoml/ops/docker/alpine/Dockerfile
- tests/smoke/smoke.js
@groovytron Could you please give it a try? Does it fix #32?
> Install dependencies in the container

- blockdiag/src/backend/diag.py
> resolves #39 set dimensions on BlockDiag, NwDiag, ActDiag and SeqDiag SVG

- README.adoc
- blockdiag/README.adoc
- blockdiag/examples.py
- blockdiag/src/server.py
- docs/modules/setup/pages/install.adoc
- server/README.adoc
- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- server/src/main/resources/web/hello.html
- tests/smoke/diagrams/packet.diag
- tests/smoke/diagrams/rack.diag
- tests/smoke/smoke.js
> resolves #50 add packetdiag and rackdiag

- README.adoc
- docs/modules/ROOT/pages/architecture.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/setup/pages/kroki-cli.adoc
- docs/modules/setup/pages/manual-install.adoc
- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- server/src/main/java/io/kroki/server/service/Vega.java
- server/src/main/resources/web/hello.html
- server/src/test/java/io/kroki/server/service/VegaServiceTest.java
- tests/smoke/diagrams/discretizing-scale.vlite
- tests/smoke/smoke.js
- vega/index.js
- vega/package-lock.json
- vega/package.json
> resolves #57 add support for Vega-Lite diagrams

- Makefile
- docs/modules/ROOT/pages/architecture.adoc
- docs/modules/ROOT/pages/diagrams-types.adoc
- server/ops/docker/jdk8-alpine/Dockerfile
- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- server/src/main/java/io/kroki/server/service/Wavedrom.java
- server/src/test/java/io/kroki/server/service/WavedromServiceTest.java
- tests/smoke/diagrams/wavedrom.json5
- tests/smoke/smoke.js
- wavedrom/.gitignore
- wavedrom/Makefile
- wavedrom/index.js
- wavedrom/ops/docker/alpine/Dockerfile
- wavedrom/package-lock.json
- wavedrom/package.json
> resolves #107 add wavedrom

- tests/smoke/smoke.js
- vega/ops/docker/alpine/Dockerfile
Revert to `node:10.15.0-alpine` and add a smoke tests to avoid regression.
> Node canvas does not compile on node:12.16.1-alpine

- pom.xml
- server/pom.xml
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- server/src/main/resources/application.properties
- server/src/main/resources/web/hello.html
- server/src/main/resources/web/root/css/main.css
- umlet/pom.xml
> resolves #117 add Kroki version and SHA1 to hello page

- mermaid/Dockerfile
- nomnoml/ops/docker/alpine/Dockerfile
- server/Makefile
- server/ops/docker/jdk11-alpine/Dockerfile
- server/ops/docker/ld-musl-x86_64.path
- tests/smoke/docker-compose.yaml
- vega/ops/docker/alpine/Dockerfile
- wavedrom/ops/docker/alpine/Dockerfile
> resolves #19 use AdoptOpenJDK JRE 11 on Alpine 3.11

- Makefile
- bytefield/.gitignore
- bytefield/Makefile
- bytefield/index.js
- bytefield/ops/docker/alpine/Dockerfile
- bytefield/package-lock.json
- bytefield/package.json
- bytefield/test.edn
- docs/modules/ROOT/pages/architecture.adoc
- docs/modules/ROOT/pages/diagrams-types.adoc
- server/ops/docker/jdk11-alpine/Dockerfile
- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/service/Bytefield.java
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- tests/smoke/diagrams/bytefield.bf
- tests/smoke/smoke.js
> resolves #139 add support for bytefield

- README.adoc
Forgot to update the README in my PR so here is another one.
> updated README.adoc for bpmn

- server/src/main/java/io/kroki/server/log/Logging.java
> resolves #30 add User-Agent in logging MDC

- mermaid/examples/class.mermaid
- mermaid/examples/er.mermaid
- mermaid/examples/flow.mermaid
- mermaid/examples/gantt.mermaid
- mermaid/examples/journey.mermaid
- mermaid/examples/pie.mermaid
- mermaid/examples/sequence.mermaid
- mermaid/examples/state.mermaid
- mermaid/src/task.js
> resolves #151 use an explicit height and width

- docs/modules/setup/examples/encode.php
- docs/modules/setup/pages/encode-diagram.adoc
> resolves #506 add an example on how to encode using PHP

- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/service/Ditaa.java
> Use executeBlocking block to avoid blocking the event loop thread

- docs/modules/setup/pages/configuration.adoc
- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/service/Plantuml.java
Also introduce a new option to configure a timeout.
> Configure timeout and use executeBlocking on PlantUML

- server/src/main/java/io/kroki/server/service/Plantuml.java
- server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java
> resolves #578 preserve PlantUML stdlib: archimate, logos and elastic

- server/ops/docker/jdk11-alpine/Dockerfile
- server/src/test/java/io/kroki/server/decode/DiagramSourceTest.java
- server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java
- tests/smoke/diagrams/chinese.puml
- tests/smoke/smoke.js
> resolves #574 install a chinese font

- server/src/main/java/io/kroki/server/action/Delegator.java
> resolves #609 remove the extra call to the delegate handler

- blockdiag/Dockerfile
- bpmn/Dockerfile
- excalidraw/Dockerfile
- mermaid/Dockerfile
- server/ops/docker/jdk11-alpine/Dockerfile
User and group added and home dir as workdir.
> Dockerfile with user kroki and kroki as owner

- docs/modules/setup/pages/configuration.adoc
- server/src/main/java/io/kroki/server/Server.java
- server/src/test/java/io/kroki/server/ServerTest.java
- server/src/test/java/io/kroki/server/ServerUriResponseTest.java
Proposal for https://github.com/yuzutech/kroki/issues/555
> Make the max URI length configurable

- tests/smoke/diagrams/bitfield.json5
- tests/smoke/smoke.js
> resolves #648 make sure that bitfield diagrams (WaveDrom) are supported

- server/src/main/resources/c4.puml
- server/src/main/resources/c4_component.puml
- server/src/main/resources/c4_container.puml
- server/src/main/resources/c4_context.puml
- server/src/main/resources/c4_deployment.puml
- server/src/main/resources/c4_dynamic.puml
> #675: Update C4 definition files

- server/src/main/java/io/kroki/server/action/DitaaContext.java
- server/src/main/java/io/kroki/server/log/Logging.java
- server/src/main/java/io/kroki/server/service/Plantuml.java
- server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java
> resolves #689 delegate to ditaa

- Makefile
Hello @Mogztter 
This tiny pull request allows to improve quality and readability in main Makefile!
Happy code reviewing!
> Tiny updates in main Makefile

- server/src/main/resources/c4_component.puml
- server/src/main/resources/c4_container.puml
- server/src/main/resources/c4_context.puml
- server/src/main/resources/c4_deployment.puml
- server/src/main/resources/c4_dynamic.puml
- server/src/test/java/io/kroki/server/service/C4PlantumlServiceTest.java
To resolve https://github.com/yuzutech/kroki/issues/718
> remove the include part in c4 .puml files

- server/src/main/resources/c4.puml
- server/src/main/resources/c4_component.puml
- server/src/main/resources/c4_container.puml
- server/src/main/resources/c4_context.puml
- server/src/main/resources/c4_deployment.puml
- server/src/main/resources/c4_dynamic.puml
> resolves #747 upgrade C4 PlantUML to 2.2.0

- server/src/main/java/io/kroki/server/action/Commander.java
In theory, the result should always be sent to `stdout`. We still need to read `stderr` to return a meaningful error message in case the command fails.
> ref #767 do not redirect stderr to stdout

- docs/antora.yml
- server/ops/docker/build-static-erd
- server/src/main/java/io/kroki/server/service/HealthHandler.java
> resolves #843 upgrade Erd to version 0.2.1.0

- docs/modules/ROOT/pages/index.adoc
- docs/modules/setup/nav.adoc
- docs/modules/setup/pages/third-party-tools.adoc
Related to this comment https://github.com/yuzutech/kroki/issues/867#issuecomment-915788485
> Add Diagram it mentioning to docs

- docs/modules/setup/examples/Encode.java
- server/src/main/java/io/kroki/server/decode/DiagramSource.java
- server/src/main/java/io/kroki/server/decode/Zlib.java
- server/src/test/java/io/kroki/server/decode/DiagramSourceTest.java
- server/src/test/java/io/kroki/server/decode/ZlibTest.java
Reference: https://github.com/DaveJarvis/keenwrite/issues/138
> Fix the deflate implementation in Java

- server/src/main/resources/c4.puml
- server/src/main/resources/c4_context.puml
- server/src/main/resources/c4_deployment.puml
Copied from: https://github.com/plantuml-stdlib/C4-PlantUML/tree/v2.3.0
resolves #920
> resolves #920 upgrade C4 PlantUML definition files to 2.3.0

- server/src/main/resources/c4.puml
- server/src/main/resources/c4_component.puml
- server/src/main/resources/c4_container.puml
- server/src/main/resources/c4_context.puml
- server/src/main/resources/c4_deployment.puml
- server/src/main/resources/c4_dynamic.puml
Copied from: https://github.com/plantuml-stdlib/C4-PlantUML/tree/v2.4.0
resolves #1055
> resolves #1055 upgrade C4 PlantUML definition files to 2.4.0

- server/src/main/java/io/kroki/server/error/ErrorContext.java
- server/src/main/java/io/kroki/server/error/ErrorHandler.java
- server/src/main/java/io/kroki/server/service/HelloHandler.java
- server/src/main/java/io/kroki/server/service/Mermaid.java
- server/src/main/java/io/kroki/server/service/Structurizr.java
- server/src/test/java/io/kroki/server/ServerSSLTest.java
- server/src/test/java/io/kroki/server/decode/DiagramSourceTest.java
- server/src/test/java/io/kroki/server/error/ErrorHandlerTest.java
- server/src/test/java/io/kroki/server/service/GraphVizServiceTest.java
- server/src/test/java/io/kroki/server/service/HelloServiceTest.java
VSCode listed the following imports as unused.
> Remove unused imports

- server/ops/docker/jdk11-alpine/Dockerfile
> resolves #1137 upgrade to eclipse-temurin:11.0.14_9-jre-alpine

- README.adoc
following up at https://github.com/yuzutech/kroki/pull/149
> doc: use expose instead of ports in docker-compose.yml

- docs/modules/ROOT/pages/project/get-help.adoc
From Gitter to Zulip
Relates to https://github.com/yuzutech/docs.kroki.io/pull/16
> use zulip for chat

- server/src/main/java/io/kroki/server/action/Delegator.java
- server/src/main/java/io/kroki/server/service/Blockdiag.java
- server/src/main/java/io/kroki/server/service/Bpmn.java
- server/src/main/java/io/kroki/server/service/Diagramsnet.java
- server/src/main/java/io/kroki/server/service/Excalidraw.java
- server/src/main/java/io/kroki/server/service/Mermaid.java
- server/src/test/java/io/kroki/server/action/DelegatorTest.java
> resolves #1251 propagate diagram options

- mermaid/src/worker.js
- mermaid/tests/test.js
> resolves #1253 use textContent to properly handle <> characters

- server/pom.xml
- server/src/main/java/io/kroki/server/error/ErrorHandler.java
> resolves #1280 sanitize error messages returned as HTML

- docs/modules/setup/pages/third-party-tools.adoc
Hey, thanks for the awesome work ! I've build a vscode extension to be able to preview my kroki from a markdown file, I think it deserves a mention :)
> Add mention of the Markdown Kroki extension

- docs/modules/setup/pages/encode-diagram.adoc
In line with the examples in other programming languages I have added one in Tcl.
> Example of usage with Tcl

- docs/modules/setup/pages/configuration.adoc
- server/src/main/java/io/kroki/server/Server.java
- server/src/test/java/io/kroki/server/ServerConfigTest.java
add support for domain socket addresses. see issue _**allow binding to unix socket**_ https://github.com/yuzutech/kroki/issues/1329
> Support domain sockets

- .github/workflows/main.yaml
- .github/workflows/release.yml
Remove [Setup Docker] step, setup-buildx-action is preferred
- Reduce steps 
- Version matching between client and server
Example: https://github.com/arukiidou/sshpass-docker/blob/main/.github/workflows/main.yaml
> remove [Setup Docker] step

- .github/workflows/dockerhub-description.yml
add docker description 
resolves: #1382
> add docker hub description on diagramsnet image

- wireviz/Dockerfile
> add missing font package to wireviz container

- docs/modules/setup/pages/configuration.adoc
- server/src/main/java/io/kroki/server/Server.java
- server/src/test/java/io/kroki/server/ServerCorsTest.java
> resolves #1449 allow to configure additional allowed headers (CORS) using config

- server/pom.xml
> resolves #1441 add Netty native transport (to use socket listening)

- server/ops/docker/jdk11-jammy/Dockerfile
Resolves https://github.com/yuzutech/kroki/issues/1542
> add OCI labels to Kroki Dockerfile

- ci/tasks/update-versions.js
- ci/tests/diagrams/class.puml
- ci/tests/smoke.js
- docs/antora.yml
- server/ops/docker/jdk11-jammy/Dockerfile
- server/src/main/java/io/kroki/server/service/Plantuml.java
> resolves #1546 upgrade PlantUML to v1.2023.7

- docs/modules/setup/pages/diagram-options.adoc
> Revert "D2 diagrams: document option 'sketch'"

- excalidraw/Dockerfile
- excalidraw/package-lock.json
- excalidraw/package.json
- excalidraw/src/browser-instance.js
- excalidraw/src/index.js
- excalidraw/src/logger.js
- excalidraw/src/task.js
- excalidraw/src/worker.js
> resolves #1561 add logger in kroki-excalidraw

- mermaid/Dockerfile
- mermaid/package-lock.json
- mermaid/package.json
- mermaid/src/browser-instance.js
We are now using https://developer.chrome.com/articles/new-headless/ 🎉
> Mermaid: Upgrade Alpine to 3.18

- docs/antora.yml
- server/ops/docker/jdk11-jammy/Dockerfile
- server/src/main/java/io/kroki/server/service/Bpmn.java
- server/src/main/java/io/kroki/server/service/D2.java
- server/src/main/java/io/kroki/server/service/Mermaid.java
- server/src/main/java/io/kroki/server/service/Nomnoml.java
- server/src/main/java/io/kroki/server/service/Vega.java
https://github.com/terrastruct/d2/releases/tag/v0.5.1
> Update D2 to 0.5.1

- wireviz/requirements.txt
> Fix wireviz build due to pyyaml install failure

- docs/antora.yml
- server/README.adoc
- server/ops/docker/jdk11-jammy/Dockerfile
- server/src/main/java/io/kroki/server/service/Plantuml.java
- server/src/test/java/io/kroki/server/DownloadPlantumlNativeImage.java
- server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java
resolves #1606
Also includes openiconic icons.
> resolves #1606 upgrade PlantUML to 1.2023.10

- tikz/tikz2svg
> resolves #1553 extract error message

- bpmn/Dockerfile
- bpmn/package-lock.json
- bpmn/package.json
- bpmn/src/browser-instance.js
- bpmn/src/index.js
- bpmn/src/logger.js
- bpmn/src/task.js
- bpmn/src/worker.js
- diagrams.net/Dockerfile
- diagrams.net/package-lock.json
- diagrams.net/package.json
- diagrams.net/src/browser-instance.js
- diagrams.net/src/index.js
- diagrams.net/src/logger.js
- diagrams.net/src/task.js
- diagrams.net/src/worker.js
- excalidraw/src/index.js
- mermaid/src/index.js
- mermaid/src/worker.js
- mermaid/test/convert-test.mjs
- server/src/main/java/io/kroki/server/action/Delegator.java
- server/src/main/java/io/kroki/server/error/BadRequestException.java
- server/src/main/java/io/kroki/server/error/ErrorHandler.java
- Allow to return the complete error from companion containers
- Add a convert timeout on all companion containers (bpmn, excalidraw, mermaid and diagrams.net)
- Add logger on all companion containers
- Make a distinction between unexpected errors and bad syntax errors
- Switch to ESM
> Companion containers return JSON response

- server/src/main/java/io/kroki/server/error/ErrorHandler.java
- server/src/main/java/io/kroki/server/error/MethodNotAllowedException.java
- server/src/main/java/io/kroki/server/service/DiagramRegistry.java
> resolves #1621 return status 405

- diagrams.net/src/worker.js
- mermaid/src/worker.js
> resolves #1641 Mermaid background on span elements were missing

- mermaid/src/worker.js
- mermaid/test/convert-test.mjs
> resolves #1632 workaround to produce valid xhtml

- .github/workflows/cve-scan.yml
- .github/workflows/dockerhub-description.yml
- DOCKERHUB.md
- docs/modules/ROOT/pages/architecture.adoc
- docs/modules/setup/examples/kroki-docker-compose.yml
- docs/modules/setup/pages/configuration.adoc
- docs/modules/setup/pages/install.adoc
- docs/modules/setup/pages/use-kubernetes.adoc
Removes blockdiag service
Completes wireviz configuration
> Remove blockdiag and wireviz containers references

- docs/modules/setup/pages/third-party-tools.adoc
- https://www.npmjs.com/package/remark-kroki
- https://github.com/nice-move/remark-kroki
> Add remark-kroki to list of 3rd-party tools

- bpmn/package-lock.json
- bpmn/package.json
> chore(deps): update bpmn-js to 17.6.0

- docs/modules/setup/pages/configuration.adoc
Add documentation about new environment variable as suggested on https://github.com/yuzutech/kroki/pull/1761#issuecomment-2242604257
> Add KROKI_MAX_BODY_SIZE variable documentation

- .github/workflows/docs-ci.yml
- docs/modules/setup/pages/diagram-options.adoc
This should close https://github.com/yuzutech/kroki/issues/169
> chore(docs): add Ditaa diagram options to diagram-options page

- docs/modules/setup/pages/use-kubernetes.adoc
- added helm deploy subsection
- fixed broken commands in `Create objects individually` section
- uppercased Kubernetes for consistency
- other minor typos and text/punctuation revise
closes #1176
> chore(docs): introduce helm deploy method in use kubernetes section

- Taskfile.yml
Fix windows build using mavenBuild, using the correct script for windows mvnw.cmd
> Update Taskfile.yml - Fix windows build using mavenBuild

- server/src/main/java/io/kroki/server/Server.java
- server/src/main/java/io/kroki/server/action/AllowAnyMethodRedirectHandler.java
- server/src/main/java/io/kroki/server/action/Delegator.java
- server/src/main/java/io/kroki/server/service/Bpmn.java
- server/src/main/java/io/kroki/server/service/Diagramsnet.java
- server/src/main/java/io/kroki/server/service/Excalidraw.java
- server/src/main/java/io/kroki/server/service/Mermaid.java
- server/src/test/java/io/kroki/server/action/DelegatorTest.java
> feat: Allow redirect to companion server

- docs/modules/setup/pages/configuration.adoc
- server/pom.xml
- server/src/main/java/io/kroki/server/Main.java
> feat: Open Telemetry tracer

- ci/tests/smoke.js
- server/src/main/java/io/kroki/server/service/Erd.java
This might work, but I could not build kroki docker image in my environment (`sudo task dockerBuildImages` never finish).
Does any one can test it?
> fix: Erd with output format jpeg doesn't work #1895
